const seoConfig = {
  MASTER_NAME: "{{MASTER_NAME}}",
  MASTER_TITLE: "{{MASTER_TITLE}}",
  MASTER_DESCRIPTION: "{{MASTER_DESCRIPTION}}",
  MASTER_PHONE: "{{MASTER_PHONE}}",
  MASTER_EMAIL: "{{MASTER_EMAIL}}",
  SITE_URL: "{{SITE_URL}}",
  SITE_TITLE: "{{SITE_TITLE}}",
  SITE_DESCRIPTION: "{{SITE_DESCRIPTION}}",
  SITE_KEYWORDS: "{{SITE_KEYWORDS}}",
  TELEGRAM_URL: "{{TELEGRAM_URL}}",
  WHATSAPP_URL: "{{WHATSAPP_URL}}",
  VIBER_URL: "{{VIBER_URL}}",
  INSTAGRAM_URL: "{{INSTAGRAM_URL}}",
  TIKTOK_URL: "{{TIKTOK_URL}}",
};

export default seoConfig;
